-- MySQL Script generated by MySQL Workbench
-- mer. 25 mars 2015 11:52:24 CET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema base_13002155
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema base_13002155
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `base_13002155` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `base_13002155` ;

-- -----------------------------------------------------
-- Table `base_13002155`.`Enseignant`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `base_13002155`.`Enseignant` (
  `idEnseignant` INT NOT NULL,
  `nom` VARCHAR(45) NULL,
  `prenom` VARCHAR(45) NULL,
  PRIMARY KEY (`idEnseignant`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `base_13002155`.`Cours`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `base_13002155`.`Cours` (
  `idCours` INT NOT NULL,
  `nom` VARCHAR(45) NULL,
  PRIMARY KEY (`idCours`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `base_13002155`.`Enseigne`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `base_13002155`.`Enseigne` (
  `Cours_idCours` INT NOT NULL,
  `Enseignant_idEnseignant` INT NOT NULL,
  PRIMARY KEY (`Cours_idCours`, `Enseignant_idEnseignant`),
  INDEX `fk_Enseigne_Enseignant1_idx` (`Enseignant_idEnseignant` ASC),
  CONSTRAINT `fk_Enseigne_Cours`
    FOREIGN KEY (`Cours_idCours`)
    REFERENCES `base_13002155`.`Cours` (`idCours`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Enseigne_Enseignant1`
    FOREIGN KEY (`Enseignant_idEnseignant`)
    REFERENCES `base_13002155`.`Enseignant` (`idEnseignant`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `base_13002155`.`Parcours`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `base_13002155`.`Parcours` (
  `idPar` INT NOT NULL,
  `nom` VARCHAR(45) NULL,
  PRIMARY KEY (`idPar`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `base_13002155`.`Etudiant`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `base_13002155`.`Etudiant` (
  `idEtudiant` INT NOT NULL,
  `nom` VARCHAR(45) NULL,
  `prenom` VARCHAR(45) NULL,
  `Parcours_idPar` INT NOT NULL,
  PRIMARY KEY (`idEtudiant`, `Parcours_idPar`),
  INDEX `fk_Etudiant_Parcours1_idx` (`Parcours_idPar` ASC),
  CONSTRAINT `fk_Etudiant_Parcours1`
    FOREIGN KEY (`Parcours_idPar`)
    REFERENCES `base_13002155`.`Parcours` (`idPar`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `base_13002155`.`estInscrit`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `base_13002155`.`estInscrit` (
  `Etudiant_idEtudiant` INT NOT NULL,
  `Cours_idCours` INT NOT NULL,
  PRIMARY KEY (`Etudiant_idEtudiant`, `Cours_idCours`),
  INDEX `fk_estInscrit_Etudiant1_idx` (`Etudiant_idEtudiant` ASC),
  INDEX `fk_estInscrit_Cours1_idx` (`Cours_idCours` ASC),
  CONSTRAINT `fk_estInscrit_Etudiant1`
    FOREIGN KEY (`Etudiant_idEtudiant`)
    REFERENCES `base_13002155`.`Etudiant` (`idEtudiant`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_estInscrit_Cours1`
    FOREIGN KEY (`Cours_idCours`)
    REFERENCES `base_13002155`.`Cours` (`idCours`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `base_13002155`.`Salle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `base_13002155`.`Salle` (
  `idSalle` INT NOT NULL,
  PRIMARY KEY (`idSalle`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `base_13002155`.`estDans`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `base_13002155`.`estDans` (
  `Cours_idCours` INT NOT NULL,
  `Salle_idSalle` INT NOT NULL,
  `horaire` DATE NOT NULL,
  PRIMARY KEY (`Cours_idCours`, `Salle_idSalle`),
  INDEX `fk_estDans_Cours1_idx` (`Cours_idCours` ASC),
  INDEX `fk_estDans_Salle1_idx` (`Salle_idSalle` ASC),
  CONSTRAINT `fk_estDans_Cours1`
    FOREIGN KEY (`Cours_idCours`)
    REFERENCES `base_13002155`.`Cours` (`idCours`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_estDans_Salle1`
    FOREIGN KEY (`Salle_idSalle`)
    REFERENCES `base_13002155`.`Salle` (`idSalle`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `base_13002155`.`suit`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `base_13002155`.`suit` (
  `Parcours_idPar` INT NOT NULL,
  PRIMARY KEY (`Parcours_idPar`),
  CONSTRAINT `fk_suit_Parcours1`
    FOREIGN KEY (`Parcours_idPar`)
    REFERENCES `base_13002155`.`Parcours` (`idPar`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
